// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLlHowC7dfb5sLbNIGqQo85zlNwuBBcN4',
    appId: '1:938112286613:web:1706d8252f82efebda009c',
    messagingSenderId: '938112286613',
    projectId: 'focus-ted-alv-189bf',
    authDomain: 'focus-ted-alv-189bf.firebaseapp.com',
    storageBucket: 'focus-ted-alv-189bf.firebasestorage.app',
    measurementId: 'G-5G2V0TFTR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE-REmvjZv4xO2qzHKyrWCOhvwNZNYe8g',
    appId: '1:938112286613:android:2f42aa0e950d62cada009c',
    messagingSenderId: '938112286613',
    projectId: 'focus-ted-alv-189bf',
    storageBucket: 'focus-ted-alv-189bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ECxPgZjg77ilaubiPN4uOE5Bqfl7mFQ',
    appId: '1:938112286613:ios:29ac663ae40a5652da009c',
    messagingSenderId: '938112286613',
    projectId: 'focus-ted-alv-189bf',
    storageBucket: 'focus-ted-alv-189bf.firebasestorage.app',
    iosBundleId: 'com.example.alv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ECxPgZjg77ilaubiPN4uOE5Bqfl7mFQ',
    appId: '1:938112286613:ios:29ac663ae40a5652da009c',
    messagingSenderId: '938112286613',
    projectId: 'focus-ted-alv-189bf',
    storageBucket: 'focus-ted-alv-189bf.firebasestorage.app',
    iosBundleId: 'com.example.alv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLlHowC7dfb5sLbNIGqQo85zlNwuBBcN4',
    appId: '1:938112286613:web:071e3f8609585c49da009c',
    messagingSenderId: '938112286613',
    projectId: 'focus-ted-alv-189bf',
    authDomain: 'focus-ted-alv-189bf.firebaseapp.com',
    storageBucket: 'focus-ted-alv-189bf.firebasestorage.app',
    measurementId: 'G-78H64MSPT7',
  );
}
